Feat/delete table
j-yesung/magic-pos pull request #48
Opened 2024-01-10 16:22 UTC by LeeDongTak

2024-01-10 16:25 UTC, j-yesung approved these changes

2024-01-10 16:29 UTC, 4anghyeon requested changes

2024-01-10 16:29 UTC, 4anghyeon commented on src/components/table/TableContainer.tsx
> +              return a.position < b.position ? -1 : 1 as number
삼항연산의 결과는 무조건 -1 아니면 1로 number인데 굳이 as number를 붙여주신 이유가 있을까요?

2024-01-10 16:29 UTC, 4anghyeon commented on src/components/table/tableSideBar/SideBarButtonBox.tsx
> +    if (window.confirm("정말로 삭제하시겠습니까?")) {
custom hook 이용 부탁드립니다. 

```ts
MagicModal.confirm({ content: '안녕하세요', confirmButtonCallback: () => {alert('yes!!')} })
```

2024-01-11 01:59 UTC, LeeDongTak commented on src/components/table/TableContainer.tsx
> +              return a.position < b.position ? -1 : 1 as number
타입처리 하다가 붙혀놓은것데 지우는걸 깜빡했습니다

2024-01-11 06:14 UTC, LeeDongTak commented on src/components/table/TableContainer.tsx
> +              return a.position < b.position ? -1 : 1 as number
삭제 했습니다.

2024-01-11 06:15 UTC, LeeDongTak commented on src/components/table/tableSideBar/SideBarButtonBox.tsx
> +    if (window.confirm("정말로 삭제하시겠습니까?")) {
커스텀 모달 적용 했습니다.

2024-01-11 11:29 UTC, 4anghyeon approved these changes
<img src="https://media3.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

2024-01-11 11:29 UTC, merged